/* Minha Saúde IA — módulo Familiares V5.78 */
(function(){
'use strict';
const K=window.MSA_K||window.K||{};
const storage=window.MSAStorage;
const KEY=K.familiares||'msa2_familiares',SELECTED='msa2_familiar_selecionado';
function getList(){try{const v=storage.get(KEY);return Array.isArray(v)?v:[]}catch(e){return[]}}
function saveList(v){try{return storage.set(KEY,Array.isArray(v)?v:[])}catch(e){return false}}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function uid(p){return p+'_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,8)}
function val(id){const x=document.getElementById(id);return x?(x.value||'').trim():''}
function fmtDate(x){if(!x)return'Não informada';const s=String(x).slice(0,10),m=s.match(/^(\d{4})-(\d{2})-(\d{2})$/);return m?m[3]+'/'+m[2]+'/'+m[1]:String(x)}
function selectedId(){try{return storage.get(SELECTED)||''}catch(e){return''}}
function setSelected(id){try{storage.set(SELECTED,id||'')}catch(e){}}
function findMember(id){return getList().find(x=>x.id===id)||null}
function ensure(p){p.medicamentos=Array.isArray(p.medicamentos)?p.medicamentos:[];p.consultas=Array.isArray(p.consultas)?p.consultas:[];p.crises=Array.isArray(p.crises)?p.crises:[];return p}
function renderFamiliares(){
 const box=document.getElementById('familiares');if(!box||!box.classList.contains('active'))return;
 const list=getList();let sel=findMember(selectedId());if(!sel&&list.length){sel=list[0];setSelected(sel.id)}if(sel)ensure(sel);
 const cards=document.getElementById('familiaresList');
 if(cards)cards.innerHTML=list.length?list.map(p=>'<button type="button" class="familiar-person-card '+(sel&&p.id===sel.id?'selected':'')+'" onclick="selecionarFamiliar(\''+esc(p.id)+'\')"><span class="familiar-person-icon">'+(p.sexo==='Feminino'?'👩':'👤')+'</span><span class="familiar-person-info"><b>'+esc(p.nome||'Sem nome')+'</b><small>'+esc(p.parentesco||'Parentesco não informado')+'</small><small>'+esc(p.condicao||'Condição não informada')+'</small></span><span class="familiar-person-count">'+(p.medicamentos||[]).length+' 💊<br>'+(p.consultas||[]).length+' 👨‍⚕️</span></button>').join(''):'<div class="empty">Nenhum familiar cadastrado ainda.</div>';
 const detail=document.getElementById('familiarDetalhe');if(!detail)return;
 if(!sel){detail.innerHTML='<div class="empty">👨‍👩‍👧‍👦 Selecione um familiar ou cadastre o primeiro acima.</div>';return}
 const meds=sel.medicamentos||[],cons=sel.consultas||[],crises=sel.crises||[];
 detail.innerHTML='<div class="familiar-detail-head"><div><div class="familiar-kicker">PESSOA ACOMPANHADA</div><h2>👤 '+esc(sel.nome||'Sem nome')+'</h2><div class="muted">'+esc(sel.parentesco||'Parentesco não informado')+(sel.idade?' · '+esc(sel.idade)+' anos':'')+'</div></div><div class="row"><button type="button" class="btn secondary small" onclick="copiarResumoFamiliar(\''+esc(sel.id)+'\')">🤖 Copiar resumo</button><button type="button" class="btn red small" onclick="excluirFamiliar(\''+esc(sel.id)+'\')">🗑️ Excluir</button></div></div>'+
 '<div class="familiar-alert"><b>🧠 '+esc(sel.condicao||'Condição de saúde não informada')+'</b><br><span>'+esc(sel.obs||'Use esta área para organizar o cuidado.')+'</span></div>'+
 '<div class="familiar-summary-grid"><div><span>🎂 Nascimento</span><b>'+esc(fmtDate(sel.nasc))+'</b></div><div><span>🩸 Sangue</span><b>'+esc(sel.sangue||'Não informado')+'</b></div><div><span>🚨 Alergias</span><b>'+esc(sel.alergias||'Não informado')+'</b></div><div><span>📞 Contato</span><b>'+esc(sel.contato||'Não informado')+'</b></div></div>'+
 '<div class="familiar-grid">'+
 '<div class="card familiar-subcard"><h3>💊 Medicamentos</h3><div class="muted">Nome, dose, horário e observações.</div><form id="familiarMedForm" style="margin-top:10px"><div class="grid2"><label>Medicamento<input id="fMedNome" required></label><label>Dose<input id="fMedDose"></label></div><div class="grid2"><label>Horário<input id="fMedHora" type="time"></label><label>Frequência<input id="fMedFreq"></label></div><label>Prescrito por<input id="fMedPres"></label><label>Observações<textarea id="fMedObs"></textarea></label><button class="btn">💾 Adicionar medicamento</button></form><div class="list" style="margin-top:12px">'+(meds.length?meds.slice().reverse().map(x=>'<div class="item"><div class="itemtop"><b>💊 '+esc(x.nome)+'</b><button type="button" class="btn red small" onclick="excluirRegistroFamiliar(\''+esc(sel.id)+'\',\'medicamentos\',\''+esc(x.id)+'\')">Excluir</button></div><p>'+esc(x.dose||'Dose não informada')+(x.hora?' · '+esc(x.hora):'')+(x.frequencia?' · '+esc(x.frequencia):'')+'<br>'+esc(x.prescritoPor||'')+'<br>'+esc(x.obs||'')+'</p></div>').join(''):'<div class="empty">Nenhum medicamento registrado.</div>')+'</div></div>'+
 '<div class="card familiar-subcard"><h3>👨‍⚕️ Consultas</h3><div class="muted">Consultas, retornos e orientações.</div><form id="familiarConsultaForm" style="margin-top:10px"><div class="grid2"><label>Data<input id="fConData" type="date" required></label><label>Especialidade<input id="fConEsp" required></label></div><div class="grid2"><label>Médico<input id="fConMed"></label><label>Próximo retorno<input id="fConRet" type="date"></label></div><label>Motivo<textarea id="fConMot"></textarea></label><label>Orientações recebidas<textarea id="fConObs"></textarea></label><button class="btn">💾 Registrar consulta</button></form><div class="list" style="margin-top:12px">'+(cons.length?cons.slice().reverse().map(x=>'<div class="item"><div class="itemtop"><b>👨‍⚕️ '+esc(x.especialidade||'Consulta')+'</b><span class="tag">'+esc(fmtDate(x.data))+'</span></div><p>'+esc(x.medico||'Médico não informado')+'<br>'+esc(x.motivo||'')+(x.retorno?'<br>Retorno: '+esc(fmtDate(x.retorno)):'')+'<br>'+esc(x.obs||'')+'</p><button type="button" class="btn red small" onclick="excluirRegistroFamiliar(\''+esc(sel.id)+'\',\'consultas\',\''+esc(x.id)+'\')">Excluir</button></div>').join(''):'<div class="empty">Nenhuma consulta registrada.</div>')+'</div></div></div>'+
 '<div class="card familiar-subcard" style="margin-top:13px"><h3>🚨 Crises / intercorrências</h3><div class="muted">Registre objetivamente o que aconteceu, possíveis gatilhos e o atendimento realizado.</div><form id="familiarCriseForm" style="margin-top:10px"><div class="grid2"><label>Data<input id="fCriData" type="date" required></label><label>Hora<input id="fCriHora" type="time"></label></div><div class="grid2"><label>Tipo<select id="fCriTipo"><option>Alteração de comportamento</option><option>Agitação</option><option>Confusão</option><option>Esquecimento acentuado</option><option>Agressividade</option><option>Queda</option><option>Outro</option></select></label><label>Intensidade<select id="fCriInt"><option>Leve</option><option>Moderada</option><option>Intensa</option><option>Risco imediato</option></select></label></div><label>O que aconteceu?<textarea id="fCriDesc" required></textarea></label><label>Possível gatilho<input id="fCriGatilho"></label><label>Conduta / atendimento recebido<textarea id="fCriConduta"></textarea></label><button class="btn">💾 Registrar ocorrência</button></form><div class="list" style="margin-top:12px">'+(crises.length?crises.slice().reverse().map(x=>'<div class="item '+(x.intensidade==='Risco imediato'?'danger':'')+'"><div class="itemtop"><b>🚨 '+esc(x.tipo||'Ocorrência')+'</b><span class="tag">'+esc(fmtDate(x.data))+(x.hora?' · '+esc(x.hora):'')+'</span></div><p><b>Intensidade:</b> '+esc(x.intensidade||'Não informada')+'<br>'+esc(x.descricao||'')+(x.gatilho?'<br><b>Possível gatilho:</b> '+esc(x.gatilho):'')+(x.conduta?'<br><b>Conduta/atendimento:</b> '+esc(x.conduta):'')+'</p><button type="button" class="btn red small" onclick="excluirRegistroFamiliar(\''+esc(sel.id)+'\',\'crises\',\''+esc(x.id)+'\')">Excluir</button></div>').join(''):'<div class="empty">Nenhuma crise ou intercorrência registrada.</div>')+'</div></div>';
 bindForms(sel.id);
}
function bindForms(id){
 const m=document.getElementById('familiarMedForm');if(m)m.onsubmit=e=>{e.preventDefault();addRecord(id,'medicamentos',{nome:val('fMedNome'),dose:val('fMedDose'),hora:val('fMedHora'),frequencia:val('fMedFreq'),prescritoPor:val('fMedPres'),obs:val('fMedObs')})};
 const c=document.getElementById('familiarConsultaForm');if(c)c.onsubmit=e=>{e.preventDefault();addRecord(id,'consultas',{data:val('fConData'),especialidade:val('fConEsp'),medico:val('fConMed'),retorno:val('fConRet'),motivo:val('fConMot'),obs:val('fConObs')})};
 const cr=document.getElementById('familiarCriseForm');if(cr)cr.onsubmit=e=>{e.preventDefault();addRecord(id,'crises',{data:val('fCriData'),hora:val('fCriHora'),tipo:val('fCriTipo'),intensidade:val('fCriInt'),descricao:val('fCriDesc'),gatilho:val('fCriGatilho'),conduta:val('fCriConduta')})};
}
function addRecord(memberId,type,data){const list=getList(),p=list.find(x=>x.id===memberId);if(!p)return;ensure(p);p[type].push(Object.assign({id:uid(type.slice(0,3)),criadoEm:new Date().toISOString()},data));if(!saveList(list)){alert('Não foi possível salvar.');return}setSelected(memberId);renderFamiliares()}
window.selecionarFamiliar=id=>{setSelected(id);renderFamiliares();setTimeout(()=>document.getElementById('familiarDetalhe')?.scrollIntoView({behavior:'smooth',block:'start'}),50)};
window.excluirFamiliar=id=>{const p=findMember(id);if(!p)return;if(!confirm('Excluir '+(p.nome||'este familiar')+' e todos os registros dele?'))return;const list=getList().filter(x=>x.id!==id);saveList(list);if(selectedId()===id)setSelected(list[0]?.id||'');renderFamiliares()};
window.excluirRegistroFamiliar=(memberId,type,recordId)=>{const list=getList(),p=list.find(x=>x.id===memberId);if(!p)return;ensure(p);p[type]=p[type].filter(x=>x.id!==recordId);saveList(list);setSelected(memberId);renderFamiliares()};
window.copiarResumoFamiliar=id=>{const p=findMember(id);if(!p)return;ensure(p);const t=['RESUMO DO FAMILIAR','Nome: '+(p.nome||'Não informado'),'Parentesco: '+(p.parentesco||'Não informado'),'Idade: '+(p.idade||'Não informada'),'Condição: '+(p.condicao||'Não informada'),'Alergias: '+(p.alergias||'Não informadas'),'Medicamentos:',...(p.medicamentos.length?p.medicamentos.map(x=>'- '+x.nome+(x.dose?' — '+x.dose:'')+(x.frequencia?' — '+x.frequencia:'')):['- Nenhum registrado']),'Consultas:',...(p.consultas.length?p.consultas.map(x=>'- '+fmtDate(x.data)+' — '+(x.especialidade||'Consulta')+' — '+(x.medico||'Não informado')):['- Nenhuma registrada']),'Crises:',...(p.crises.length?p.crises.map(x=>'- '+fmtDate(x.data)+' — '+(x.tipo||'Ocorrência')+' — '+(x.intensidade||'')+' — '+(x.descricao||'')):['- Nenhuma registrada'])].join('\n');if(navigator.clipboard?.writeText)navigator.clipboard.writeText(t).then(()=>alert('📋 Resumo copiado.')).catch(()=>fallback(t));else fallback(t)};
function fallback(t){const a=document.createElement('textarea');a.value=t;document.body.appendChild(a);a.select();try{document.execCommand('copy');alert('📋 Resumo copiado.')}catch(e){}a.remove()}
function init(){
 const form=document.getElementById('familiarForm');if(form)form.onsubmit=e=>{e.preventDefault();const p={id:uid('fam'),nome:val('fNome'),parentesco:val('fParentesco'),sexo:val('fSexo'),nasc:val('fNasc'),idade:val('fIdade'),condicao:val('fCondicao'),alergias:val('fAlergias'),sangue:val('fSangue'),contato:val('fContato'),obs:val('fObs'),criadoEm:new Date().toISOString(),medicamentos:[],consultas:[],crises:[]};if(!p.nome){alert('Informe o nome.');return}const list=getList();list.push(p);if(!saveList(list)){alert('Não foi possível salvar.');return}setSelected(p.id);form.reset();renderFamiliares()};
 renderFamiliares();
 const obs=new MutationObserver(()=>renderFamiliares());const section=document.getElementById('familiares');if(section)obs.observe(section,{attributes:true,attributeFilter:['class']});
}
window.renderFamiliares=renderFamiliares;
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();