/* Minha Saúde IA — camada avançada V5.38
 * Painel de evolução, padrões de registro e notificações locais.
 * Não diagnostica nem interpreta clinicamente os dados.
 */
(function(){
'use strict';
function $$(id){return document.getElementById(id)}
function getSafe(k){try{return typeof get==='function'?get(k):[]}catch(e){return[]}}
function escSafe(v){if(typeof esc==='function')return esc(v);return String(v??'').replace(/[&<>"']/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[s]))}
function dateValue(x){const v=x?.data||x?.date||x?.inicio||x?.createdAt||x?.quando||'';if(!v)return '';const d=new Date(v);return isNaN(d)?String(v).slice(0,10):d.toISOString().slice(0,10)}
function daysAgo(n){const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()-n);return d}
function inLastDays(x,n){const d=new Date(dateValue(x)+'T23:59:59');return !isNaN(d)&&d>=daysAgo(n)}
function allRecords(){const groups=[['Sintomas',getSafe(K.d),'😣'],['Consultas',getSafe(K.c),'👨‍⚕️'],['Medicamentos',getSafe(K.m),'💊'],['Exames',getSafe(K.e),'🧪'],['Sinais vitais',getSafe(K.v),'❤️'],['Vacinas',getSafe(K.vax),'💉'],['Lembretes',getSafe(K.r),'⏰'],['Documentos',getSafe(K.doc),'📄'],['Nutrição',getSafe(K.nutri),'🥗'],['Sono',getSafe(K.sono),'😴'],['Hidratação',getSafe(K.agua),'💧'],['Medidas',getSafe(K.medidas),'📏']];const out=[];groups.forEach(g=>g[1].forEach(x=>out.push({tipo:g[0],item:x,icon:g[2],data:dateValue(x)})));return out}
function profilePercent(){const p=getSafe(K.p)[0]||{};const fields=['nome','nasc','idade','peso','sexo','sangue','altura','alerg','cond','supl','info'];return Math.round(fields.filter(k=>String(p[k]??'').trim()!=='').length/fields.length*100)}
function calc(){const d=getSafe(K.d),v=getSafe(K.v),all=allRecords(),recent=all.filter(x=>inLastDays(x.item,30)),activeDays=new Set(recent.map(x=>x.data).filter(Boolean)).size,intens=d.map(x=>Number(x.int)).filter(x=>Number.isFinite(x)&&x>0),avg=intens.length?(intens.reduce((a,b)=>a+b,0)/intens.length).toFixed(1):'—',weights=[];v.forEach(x=>{const n=Number(x.peso??x.weight);if(Number.isFinite(n)&&n>0)weights.push({n,date:dateValue(x)})});const p=getSafe(K.p)[0]||{};if(Number(p.peso)>0)weights.push({n:Number(p.peso),date:'perfil'});weights.sort((a,b)=>String(a.date).localeCompare(String(b.date)));const loc={};d.forEach(x=>{const k=String(x.local||'').trim();if(k)loc[k]=(loc[k]||0)+1});const top=Object.entries(loc).sort((a,b)=>b[1]-a[1])[0];return{all,recent,activeDays,avg,weights,top,profile:profilePercent()}}
function card(t,v,d){return '<div class="msa-adv-kpi"><span>'+t+'</span><b>'+v+'</b><small>'+d+'</small></div>'}
function render(){const box=$$('msaAdvancedHome');if(!box)return;const x=calc(),w=x.weights.length?x.weights[x.weights.length-1].n+' kg':'—',prev=x.weights.length>1?x.weights[x.weights.length-2].n:null;let wd='Nenhum peso registrado';if(prev!==null){const diff=(x.weights[x.weights.length-1].n-prev).toFixed(1);wd=(diff>0?'+':'')+diff+' kg vs. registro anterior'}const pattern=x.top?escSafe(x.top[0])+' ('+x.top[1]+' registro'+(x.top[1]>1?'s':'')+')':'Ainda não há repetição suficiente';box.innerHTML='<div class="msa-adv-head"><div><div class="msa-adv-kicker">🧠 Camada inteligente</div><h2>📈 Evolução e organização</h2><p>Estatísticas dos seus próprios registros. Não é diagnóstico.</p></div><button class="btn secondary" type="button" onclick="msaAdvancedRefresh()">↻ Atualizar</button></div><div class="msa-adv-grid">'+card('📚 Registros totais',x.all.length,'em todos os módulos')+card('📅 Dias com registros',x.activeDays,'nos últimos 30 dias')+card('😣 Intensidade média',x.avg,x.avg==='—'?'sem intensidade informada':'dos sintomas registrados')+card('👤 Perfil preenchido',x.profile+'%','campos principais')+'</div><div class="msa-adv-panels"><div class="msa-adv-panel"><h3>⚖️ Peso mais recente</h3><div class="msa-adv-big">'+escSafe(w)+'</div><div class="muted">'+escSafe(wd)+'</div></div><div class="msa-adv-panel"><h3>🔎 Padrão de registros</h3><div class="msa-adv-big">'+pattern+'</div><div class="muted">Frequência por local informado nos sintomas.</div></div></div><div class="msa-adv-actions"><button class="btn" type="button" onclick="go(&quot;relatorios&quot;)">📊 Abrir relatórios</button><button class="btn secondary" type="button" onclick="go(&quot;buscar&quot;)">🔎 Buscar no histórico</button><button class="btn secondary" type="button" onclick="prepararConsulta()">🏥 Preparar consulta</button><button class="btn secondary" type="button" onclick="msaSolicitarNotificacoes()">🔔 Ativar notificações</button></div><div id="msaNotifStatus" class="msa-adv-status"></div>'}
function inject(){if($$('msaAdvancedHome'))return;const target=document.querySelector('#home .smart-summary')?.parentElement;if(!target)return;const wrap=document.createElement('div');wrap.className='card msa-advanced-card';wrap.id='msaAdvancedHome';target.parentElement.insertBefore(wrap,target.nextElementSibling);render()}
function notificationSupport(){return 'Notification' in window&&window.isSecureContext}
window.msaSolicitarNotificacoes=async function(){const status=$$('msaNotifStatus');if(!notificationSupport()){if(status)status.textContent='ℹ️ Este navegador não permite notificações web neste contexto.';return}try{let p=Notification.permission;if(p!=='granted')p=await Notification.requestPermission();if(p==='granted'){if(status)status.textContent='✅ Notificações ativadas neste navegador.';try{new Notification('Minha Saúde IA',{body:'As notificações locais estão ativadas.'})}catch(e){}localStorage.setItem('msa2_notifications','on');scheduleNextReminder()}else if(status)status.textContent='🔕 Notificações não autorizadas.'}catch(e){if(status)status.textContent='⚠️ Não foi possível ativar as notificações.'}}
function nextReminder(){const r=getSafe(K.r).filter(x=>x.data).map(x=>({data:x.data,nome:x.nome||'Lembrete',tipo:x.tipo||'Lembrete'}));r.sort((a,b)=>new Date(a.data)-new Date(b.data));return r.find(x=>new Date(x.data).getTime()>Date.now())}
let reminderTimer=null;
function scheduleNextReminder(){if(reminderTimer)clearTimeout(reminderTimer);if(!notificationSupport()||Notification.permission!=='granted')return;const n=nextReminder();if(!n)return;const ms=new Date(n.data).getTime()-Date.now();if(ms<=0||ms>2147483647)return;reminderTimer=setTimeout(()=>{try{new Notification('🔔 Minha Saúde IA',{body:n.nome+' — '+n.tipo})}catch(e){}scheduleNextReminder()},ms)}
function style(){if(document.getElementById('msaAdvancedStyle'))return;const s=document.createElement('style');s.id='msaAdvancedStyle';s.textContent='.msa-advanced-card{margin-top:13px;background:linear-gradient(145deg,#f8fbff,#fff);border-color:#dce8f7}.msa-adv-head{display:flex;justify-content:space-between;gap:15px;align-items:flex-start}.msa-adv-kicker{font-size:12px;font-weight:900;color:#2563eb;text-transform:uppercase;letter-spacing:.04em}.msa-adv-head h2{margin:3px 0}.msa-adv-head p{margin:0;color:#64748b;font-size:13px}.msa-adv-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin-top:14px}.msa-adv-kpi{padding:14px;border:1px solid #e2e8f0;border-radius:15px;background:#fff;display:flex;flex-direction:column;gap:4px}.msa-adv-kpi span{font-size:12px;color:#64748b}.msa-adv-kpi b{font-size:23px}.msa-adv-kpi small{font-size:11px;color:#64748b}.msa-adv-panels{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:10px}.msa-adv-panel{border:1px solid #e2e8f0;border-radius:15px;background:#fff;padding:15px}.msa-adv-panel h3{margin:0 0 7px}.msa-adv-big{font-size:20px;font-weight:900;margin-bottom:3px}.msa-adv-actions{display:flex;flex-wrap:wrap;gap:8px;margin-top:12px}.msa-adv-status{font-size:12px;margin-top:9px;color:#475569}body.msa-dark .msa-advanced-card,body.msa-dark .msa-adv-kpi,body.msa-dark .msa-adv-panel{background:#111827;border-color:#263244}@media(max-width:760px){.msa-adv-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.msa-adv-panels{grid-template-columns:1fr}.msa-adv-head{flex-direction:column}.msa-adv-actions .btn{flex:1 1 45%}}';document.head.appendChild(s)}
window.msaAdvancedRefresh=function(){style();render();scheduleNextReminder()}
function boot(){style();inject();scheduleNextReminder()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot()
})();